version: '2.0'
services:
  php-apache-environment:
    container_name: acl-php
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80

  db:
    volumes:
      - ./DATABASE/crud.sql:/docker-entrypoint-initdb.d/crud.sql
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: admin
      MYSQL_PASSWORD: ACL_GROUP_1
    ports:
      - "9906:3306"
    command: ["--init-file", "/docker-entrypoint-initdb.d/crud.sql"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db